### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by sf2020-LATTE** [riqui0130/fleamarket_sample_79a#42]
■ URL
IPアドレス：http://54.95.207.189/
Github（最終課題のリポジトリ）：https://github.com/riqui0130/fleamarket_sample_79a

■ Basic認証
ID：fleamarket_79a
Pass：namba_79a

■ テスト用アカウント
◯ 購入者用
メールアドレス：0001@gmail.com
パスワード：0001aaaa

◯ 購入用カード情報
番号：4242 4242 4242 4242
期限：02 / 28
セキュリティカード：1111

◯ 出品者用
メールアドレス：0002@gmail.com
パスワード：0002aaaa

**Comment by techcamp-N** [comment]
皆さんご提出ありがとうございます！

修正お願いしたい箇所が一点だけございます。
・ユーザー新規登録において送付先氏名のふりがなが、それぞれ名字と名前で入力できるようにして下さい。

お手数お掛け致しますが、修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by riqui0130** [comment]
修正しました！！

＞＞＞エラー出ているのでもう一度確認します

>>修正できました

**Comment by techcamp-N** [comment]
ご確認が遅くなり申し訳ありません！修正確認できましたので、LGTMとさせて頂きます！🎉

一点だけお願いです！！
明日までに出品内容・販売価格が適切な商品を3つ投稿して頂ければ幸いです！
こちらは就活に向けて企業様が見ることを意識した商品を出して下さいませ！
宜しくお願いします＾＾

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**
